# Generated by Django 4.1.3 on 2022-11-17 16:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog_posts/'),
        ),
    ]
